# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

version: '2'

services:
  postgres:
    container_name: postgres_container
    image: postgres:16.1-alpine3.18
    environment:
      POSTGRES_DB: 'notifyDB'
      POSTGRES_USER: 'puser'
      POSTGRES_PASSWORD: 'ppassword'
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
      - ./init_db:/docker-entrypoint-initdb.d
      - notifyDB-data:/var/lib/postgresql/data/pgdata
    ports:
      - '6432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U puser -d notifyDB']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:8.2
    environment:
      PGADMIN_DEFAULT_EMAIL: 'puser@mail.com'
      PGADMIN_DEFAULT_PASSWORD: 'ppassword'
      PGADMIN_CONFIG_SERVER_MODE: 'False' # To allow running in desktop mode
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - '5050:80'
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - postgres

volumes:
  notifyDB-data:
  pgadmin-data:

networks:
  postgres:
    driver: bridge
